apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-worker
  namespace: airflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-pod-role
  namespace: airflow
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - pods/exec
    - pods/status
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-pod-rolebinding
  namespace: airflow
subjects:
- kind: ServiceAccount
  name: airflow-worker
  namespace: airflow
roleRef:
  kind: Role
  name: airflow-pod-role
  apiGroup: rbac.authorization.k8s.io
