apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "watch", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: airflow-sa
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io
