ecommerce_dbt:
  outputs:
    glue:
      type: glue
      query-comment: This is a glue dbt example
      role_arn: arn:aws:iam::285560394313:role/dbt_glue_role
      region: eu-west-2
      glue_version: "4.0"
      workers: 8
      worker_type: G.1X
      idle_timeout: 10
      interactive_session: true
      schema: "dbt_glue_output_database"
      database: "dbt_glue_output_database"
      location: "s3://ti-dbt-glue-database-bucket-12345/glue-db-output/"
      session_provisioning_timeout_in_seconds: 300
      datalake_formats: "iceberg"
      conf: >
        spark.sql.defaultCatalog=glue_catalog
        --conf spark.sql.catalog.glue_catalog.warehouse=s3://ti-dbt-glue-database-bucket-12345/glue-db-output/
        --conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog
        --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
        --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
        --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
        --conf spark.sql.iceberg.handle-timestamp-without-timezone=true
        --conf spark.sql.catalog.glue_catalog.write.target-file-size-bytes=134217728
      # default_arguments: "--enable-metrics=true, --enable-continuous-cloudwatch-log=true, --enable-continuous-log-filter=true, --enable-spark-ui=true, --spark-event-logs-path=s3://my-s3-bucket/prefix/sparklogs/"

  target: glue